spring.application.name=gkys
spring.datasource.url=jdbc:mariadb://5.183.188.132:3306/2024_mysql_kon
spring.datasource.username=2024_mysql_k_usr
spring.datasource.password=KgT4gD9eWNS7Cque
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
debug=true
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web.filter=ERROR
logging.level.org.springframework.security.authentication=ERROR
logging.level.org.springframework.security.web.authentication=ERROR

api.security.token.secret=my-secret-key

server.address=0.0.0.0
server.port=8873